// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package cn.com.xcar.proto;

public interface AdvertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.xcar.proto.AdvertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 placeId = 1;</code>
   */
  boolean hasPlaceId();
  /**
   * <code>optional int32 placeId = 1;</code>
   */
  int getPlaceId();

  /**
   * <code>optional int32 platformId = 2;</code>
   */
  boolean hasPlatformId();
  /**
   * <code>optional int32 platformId = 2;</code>
   */
  int getPlatformId();
}
