// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package cn.com.xcar.proto;

public interface AdvertReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.xcar.proto.AdvertReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string msg = 1;</code>
   */
  boolean hasMsg();
  /**
   * <code>optional string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
