// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package cn.com.xcar.proto;

public final class SearchProto {
  private SearchProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_com_xcar_proto_AdvertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_com_xcar_proto_AdvertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_com_xcar_proto_AdvertReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_com_xcar_proto_AdvertReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014search.proto\022\021cn.com.xcar.proto\"4\n\rAdv" +
      "ertRequest\022\017\n\007placeId\030\001 \001(\005\022\022\n\nplatformI" +
      "d\030\002 \001(\005\"\032\n\013AdvertReply\022\013\n\003msg\030\001 \001(\t2V\n\006S" +
      "earch\022L\n\006search\022 .cn.com.xcar.proto.Adve" +
      "rtRequest\032\036.cn.com.xcar.proto.AdvertRepl" +
      "y\"\000B\"\n\021cn.com.xcar.protoB\013SearchProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_com_xcar_proto_AdvertRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_com_xcar_proto_AdvertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_com_xcar_proto_AdvertRequest_descriptor,
        new java.lang.String[] { "PlaceId", "PlatformId", });
    internal_static_cn_com_xcar_proto_AdvertReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_com_xcar_proto_AdvertReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_com_xcar_proto_AdvertReply_descriptor,
        new java.lang.String[] { "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
